baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "http://odd-daboss.github.io/rfq-resume-cards/" # the base hostname & protocol for your site

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
